### PR TITLE
Fix: check if image is loaded, before using imgRef.naturalWidth

### PR DESCRIPTION
**Pull request by b3da-cz**
resolves https://github.com/img-mapper/react-img-mapper/issues/11

### CODE REVIEW

**Comment by NishargShah** [comment]
No need to use the state for it, you can easily solve it by

```
if (responsive && parentWidth && imgRef) {
    ....
}
```

Thanks for the PR

**Comment by b3da-cz** [comment]
Np. Btw, I thought so too. You get rid of the error. But prefill won't work on first load, the way state hooks updates your component, does not allow for calling those functions in right order now

**Comment by NishargShah** [comment]
It doing multiple rerender because of `useEffect` and on that rerender it will find the `imgRef` so yes it will not prefill in the first load but it does not matter here because I m running `init` function once dom loaded.

**Comment by b3da-cz** [comment]
Nice theory, I would recommend to test it for yourself before releasing fix :)

There are multiple problems with this:
* `<image />` may and may not be (will not in most cases) loaded once DOM loaded, so:
* setting `imgRef` and calling `renderPrefilledAreas()` [here](https://github.com/img-mapper/react-img-mapper/blob/master/src/ImageMapper.tsx#L144) doesn't work the way you think (try to debug what is `imgRef` in this call - you are in _function_ component, not _class_ component), so no prefill happens there
* calling `updateCanvas()` (which calls `renderPrefilledAreas()`) [here](https://github.com/img-mapper/react-img-mapper/blob/master/src/ImageMapper.tsx#L57) will fail too in most cases (not loaded `image`, null `imgRef`)
* also, [this check](https://github.com/img-mapper/react-img-mapper/blob/master/src/ImageMapper.tsx#L291) will fail without loaded image, so no `<area />` is rendered in `<map />` that way..

**Comment by NishargShah** [comment]
Thanks, @b3da-cz, your code helped me in a lot of the cases and I merged the code of yours but in my style

**Pull request closed without merging**
